version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: discoverdollar-devops-assignment-mongo-1
    restart: unless-stopped
    # run without authentication â€“ perfect for this assignment
    command: ["mongod", "--bind_ip_all", "--noauth"]
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  backend:
    image: prasannff/dd-backend:latest
    container_name: discoverdollar-devops-assignment-backend-1
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      # your Node app can use this, or its own db.config.js with "mongo" hostname
      - MONGO_URL=mongodb://mongo:27017/dd_db
      - NODE_ENV=production
    ports:
      - "3000:3000"

  frontend:
    image: prasannff/dd-frontend:latest
    container_name: discoverdollar-devops-assignment-frontend-1
    restart: unless-stopped
    depends_on:
      - backend
    # Angular built app is served by nginx in this container on port 80
    # 4200 on host is just for debugging (optional but nice)
    ports:
      - "4200:80"

  nginx:
    image: nginx:latest
    container_name: discoverdollar-devops-assignment-nginx-1
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      # your reverse-proxy config
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    driver: bridge
